#!/usr/bin/env bash

function restoredb { cd ~/Documents/Apprentx/B12Database; ./restore-local-backup.sh }
function backupdb { cd ~/Documents/Apprentx/B12Database; ./backup-local.sh }

function bdb() { backupdb }
function rdb() { restoredb }

function customize() { nano /Users/charlot/.zshrc }
